id: IFAACD0C9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T23:27:47+00:00'
last_modified: '2022-06-08T06:29:54.725630+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1000
  title: ཞང་ཞུང་སྙན་རྒྱུད་ཀྱི་གསུང་པོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    88BE:
      image_group_id: I1CZ1516
      title: ''
      total_pages: 662
      order: 1
      base_file: 88BE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
